config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#landing'
  resources :pokemons
  resources :trainers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
  belongs_to :trainer

  validates :name, presence: true, length: { in:1..20}
  validates :pokemon_type, presence: true, length: { in:1..8}
  validates :level, presence: true, numericality: { less_than_or_equal_to: 100, greater_than: 0,  only_integer: true }
  validates :trainer_id, presence: true, numericality: { only_integer: true }
  validates :human, :acceptance => true
end

app/models/trainer.rb
class Trainer < ApplicationRecord
  has_many :pokemon

  validates :name, presence: true, length: { in:1..50}
  validates :age, presence: true, numericality: { only_integer: true }
  validates :human, :acceptance => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController
  before_action :set_pokemon, only: [:show, :edit, :update, :destroy]

  # GET /pokemons
  # GET /pokemons.json
  def index
    @pokemons = Pokemon.all
  end

  # GET /pokemons/1
  # GET /pokemons/1.json
  def show
  end

  # GET /pokemons/new
  def new
    @pokemon = Pokemon.new
  end

  # GET /pokemons/1/edit
  def edit
  end

  # POST /pokemons
  # POST /pokemons.json
  def create
    @pokemon = Pokemon.new(pokemon_params)

    respond_to do |format|
      if @pokemon.save
        format.html { redirect_to @pokemon, notice: 'Pokemon was successfully created.' }
        format.json { render :show, status: :created, location: @pokemon }
      else
        format.html { render :new }
        format.json { render json: @pokemon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pokemons/1
  # PATCH/PUT /pokemons/1.json
  def update
    respond_to do |format|
      if @pokemon.update(pokemon_params)
        format.html { redirect_to @pokemon, notice: 'Pokemon was successfully updated.' }
        format.json { render :show, status: :ok, location: @pokemon }
      else
        format.html { render :edit }
        format.json { render json: @pokemon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pokemons/1
  # DELETE /pokemons/1.json
  def destroy
    @pokemon.destroy
    respond_to do |format|
      format.html { redirect_to pokemons_url, notice: 'Pokemon was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pokemon
      @pokemon = Pokemon.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pokemon_params
      params.require(:pokemon).permit(:name, :pokemon_type, :level, :trainer_id, :human)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def landing
  end
end

app/controllers/trainers_controller.rb
class TrainersController < ApplicationController
  before_action :set_trainer, only: [:show, :edit, :update, :destroy]

  # GET /trainers
  # GET /trainers.json
  def index
    @trainers = Trainer.all
  end

  # GET /trainers/1
  # GET /trainers/1.json
  def show
  end

  # GET /trainers/new
  def new
    @trainer = Trainer.new
  end

  # GET /trainers/1/edit
  def edit
  end

  # POST /trainers
  # POST /trainers.json
  def create
    @trainer = Trainer.new(trainer_params)

    respond_to do |format|
      if @trainer.save
        format.html { redirect_to @trainer, notice: 'Trainer was successfully created.' }
        format.json { render :show, status: :created, location: @trainer }
      else
        format.html { render :new }
        format.json { render json: @trainer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trainers/1
  # PATCH/PUT /trainers/1.json
  def update
    respond_to do |format|
      if @trainer.update(trainer_params)
        format.html { redirect_to @trainer, notice: 'Trainer was successfully updated.' }
        format.json { render :show, status: :ok, location: @trainer }
      else
        format.html { render :edit }
        format.json { render json: @trainer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trainers/1
  # DELETE /trainers/1.json
  def destroy
    @trainer.destroy
    respond_to do |format|
      format.html { redirect_to trainers_url, notice: 'Trainer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trainer
      @trainer = Trainer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trainer_params
      params.require(:trainer).permit(:name, :age, :human)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pokemons_helper.rb
module PokemonsHelper
end

app/helpers/trainers_helper.rb
module TrainersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SpartaRailsArModels</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-md mb-4">
      <a class="navbar-brand">Welcome</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="https://www.pokemon.com/us/" target="_blank">Pokemon Website</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="https://facebook.com" target="_blank">Contact Us</a>
          </li>
        </ul>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/pokemons/_form.html.erb
<%= form_with(model: pokemon, local: true) do |form| %>
  <% if pokemon.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pokemon.errors.count, "error") %> prohibited this pokemon from being saved:</h2>

      <ul>
      <% pokemon.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :pokemon_type %>
    <%= form.text_field :pokemon_type %>
  </div>

  <div class="field">
    <%= form.label :level %>
    <%= form.number_field :level %>
  </div>

  <div class="field">
    <%= form.label :trainer_id %>
    <%= form.number_field :trainer_id %>
  </div>

  <div class="field"> Are you human? Tick if you are!
    <%= form.check_box :human %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pokemons/edit.html.erb
<h1>Editing Pokemon</h1>

<%= render 'form', pokemon: @pokemon %>

<h4><%= link_to 'Show', @pokemon %></h4>
<h4><%= link_to 'Back', pokemons_path %></h4>

app/views/pokemons/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pokemon</h1>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Type</th>
      <th>Level</th>
      <th>Trainer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pokemons.each do |pokemon| %>
      <tr>
        <td><%= pokemon.id %></td>
        <td><%= pokemon.name %></td>
        <td><%= pokemon.pokemon_type %></td>
        <td><%= pokemon.level %></td>
        <td><%= pokemon.trainer_id %></td>
        <td><%= link_to 'Show', pokemon %></td>
        <td><%= link_to 'Edit', edit_pokemon_path(pokemon) %></td>
        <td><%= link_to 'Destroy', pokemon, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<h4><%= link_to 'New Pokemon', new_pokemon_path %></h4>
<h4><%= link_to 'Take A Look At The Trainers', trainers_path %></h4>

app/views/pokemons/new.html.erb
<h1>New Pokemon</h1>

<%= render 'form', pokemon: @pokemon %>

<h4><%= link_to 'Back', pokemons_path %></h4>

app/views/pokemons/show.html.erb
<p id="notice"><%= notice %></p>

<h2>Your Chosen Pokemon:</h2>

<p>
  <strong>Name:</strong>
  <%= @pokemon.name %>
</p>

<p>
  <strong>Type:</strong>
  <%= @pokemon.pokemon_type %>
</p>

<p>
  <strong>Level:</strong>
  <%= @pokemon.level %>
</p>

<p>
  <strong>Trainer:</strong>
  <%= @pokemon.trainer_id %>
</p>


<h4><%= link_to 'Edit', edit_pokemon_path(@pokemon) %></h4>
<h4><%= link_to 'Back', pokemons_path %></h4>

app/views/static_pages/landing.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Pokemon/Trainer App</title>
</head>
<body class="landing_page_background">
  <div class="jumbotron">
    <h1 class="display-4">WELCOME TO MY POKEMON/TRAINER APP!</h1>
    <hr class="my-4">
    <p>Here you will be able to add and match Pokemon up to trainers that you create!</p>
    <h4><%= link_to 'Click Here To Take A Look At Some Pokemon', pokemons_path %></h4>
  </div>
</body>
</html>

app/views/trainers/_form.html.erb
<%= form_with(model: trainer, local: true) do |form| %>
  <% if trainer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(trainer.errors.count, "error") %> prohibited this trainer from being saved:</h2>

      <ul>
      <% trainer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.number_field :age %>
  </div>

  <div class="field"> Are you human? Tick if you are!
    <%= form.check_box :human %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/trainers/edit.html.erb
<h1>Editing Trainer</h1>

<%= render 'form', trainer: @trainer %>

<h4><%= link_to 'Show', @trainer %></h4>
<h4><%= link_to 'Back', trainers_path %></h4>

app/views/trainers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Trainers</h1>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Age</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trainers.each do |trainer| %>
      <tr>
        <td><%= trainer.id %></td>
        <td><%= trainer.name %></td>
        <td><%= trainer.age %></td>
        <td><%= link_to 'Show', trainer %></td>
        <td><%= link_to 'Edit', edit_trainer_path(trainer) %></td>
        <td><%= link_to 'Destroy', trainer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<h4><%= link_to 'New Trainer', new_trainer_path %></h4>
<h4><%= link_to 'Have A Look At The Pokemon', pokemons_path %></h4>

app/views/trainers/new.html.erb
<h1>New Trainer</h1>

<%= render 'form', trainer: @trainer %>

<h4><%= link_to 'Back', trainers_path %></h4>

app/views/trainers/show.html.erb
<p id="notice"><%= notice %></p>

<h2>Your Chosen Trainer:</h2>

<p>
  <strong>Name:</strong>
  <%= @trainer.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @trainer.age %>
</p>

<h4><%= link_to 'Edit', edit_trainer_path(@trainer) %></h4>
<h4><%= link_to 'Back', trainers_path %></h4>